
CREATE TABLE PROJECTS(
  ID BIGINT NOT NULL,
  PNAME VARCHAR,URL VARCHAR,
  LEAD VARCHAR,DESCRIPTION VARCHAR,
  PKEY VARCHAR,
  PCOUNTER BIGINT,
  ASSIGNEETYPE BIGINT,
  AVATAR BIGINT,
  CONSTRAINT PK_PROJECT PRIMARY KEY(ID)
)